obj-$(CONFIG_MXC_GPU_VIV) += gpu-viv/
obj-$(CONFIG_MXC_GPU_VIV_V5) += ../gpu/galcore/
obj-$(CONFIG_MXC_IPU_V3_FSL) += ipu3/
obj-$(CONFIG_MXC_ASRC) += asrc/
obj-$(CONFIG_MXC_VPU) += vpu/
obj-$(CONFIG_MXC_HDMI_CEC) += hdmi-cec/
obj-$(CONFIG_MXC_MIPI_CSI2) += mipi/
obj-$(CONFIG_MXC_MLB) += mlb/
