# Makefile for the lirc drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_LIRC_RPI)		+= lirc_rpi.o
obj-$(CONFIG_LIRC_XBOX)		+= lirc_xbox.o
obj-$(CONFIG_LIRC_ZILOG)	+= lirc_zilog.o
obj-$(CONFIG_LIRC_ATIUSB)	+= lirc_atiusb.o
